default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  password: password
  timeout: 5000

development:
  <<: *default
  database: assets_dev
  username: ubuntu
  password: password
